# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-31 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentneed',
            name='area',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentneed',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentneed',
            name='rental',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentneed',
            name='scope',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentneed',
            name='story',
            field=models.IntegerField(),
        ),
    ]
