# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-31 03:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20171031_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='desc',
            field=models.TextField(default='空', verbose_name='房屋信息描述'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_name',
            field=models.CharField(default=datetime.datetime(2017, 10, 31, 3, 4, 1, 168344, tzinfo=utc), max_length=128, verbose_name='房屋名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentneed',
            name='rent_name',
            field=models.CharField(default='null', max_length=128, verbose_name='出租房屋名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=50, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='house',
            name='community_name',
            field=models.CharField(max_length=100, verbose_name='小区名字'),
        ),
        migrations.AlterField(
            model_name='house',
            name='hourse_tel',
            field=models.CharField(max_length=15, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='房屋信息创建时间'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_number',
            field=models.IntegerField(verbose_name='租住人数'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(max_length=20, verbose_name='房屋类型'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_update',
            field=models.DateField(auto_now=True, verbose_name='房屋信息更新时间'),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_rent',
            field=models.BooleanField(verbose_name='是否出租'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='llord_ID',
            field=models.CharField(max_length=20, verbose_name='房东身份证'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='llord_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='房东信息创建时间'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='llord_name',
            field=models.CharField(max_length=5, verbose_name='房东真实姓名'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='llord_nickname',
            field=models.CharField(max_length=10, verbose_name='房东昵称'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='llord_password',
            field=models.CharField(max_length=64, unique=True, verbose_name='房东密码'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='llord_tel',
            field=models.CharField(max_length=15, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='llord_uid',
            field=models.IntegerField(unique=True, verbose_name='房东账号'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='llord_update',
            field=models.DateField(auto_now=True, verbose_name='房东信息更新时间'),
        ),
        migrations.AlterField(
            model_name='rentneed',
            name='area',
            field=models.IntegerField(verbose_name='面积'),
        ),
        migrations.AlterField(
            model_name='rentneed',
            name='number',
            field=models.IntegerField(verbose_name='租住人数'),
        ),
        migrations.AlterField(
            model_name='rentneed',
            name='rent_addr',
            field=models.CharField(max_length=50, verbose_name='出租地址'),
        ),
        migrations.AlterField(
            model_name='rentneed',
            name='rent_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='租房信息创建时间'),
        ),
        migrations.AlterField(
            model_name='rentneed',
            name='rent_type',
            field=models.CharField(max_length=20, verbose_name='房屋类型'),
        ),
        migrations.AlterField(
            model_name='rentneed',
            name='rent_update',
            field=models.DateField(auto_now=True, verbose_name='租房信息更新时间'),
        ),
        migrations.AlterField(
            model_name='rentneed',
            name='rental',
            field=models.IntegerField(verbose_name='租金'),
        ),
        migrations.AlterField(
            model_name='rentneed',
            name='scope',
            field=models.IntegerField(verbose_name='范围'),
        ),
        migrations.AlterField(
            model_name='rentneed',
            name='story',
            field=models.IntegerField(verbose_name='楼层'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateTimeField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=5, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=15, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(unique=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='用户信息创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_update',
            field=models.DateField(auto_now=True, verbose_name='用户信息更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=15, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, verbose_name='真实姓名'),
        ),
    ]
