# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-31 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20171031_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='llord_update',
            field=models.DateTimeField(auto_now=True, verbose_name='房东信息更新时间'),
        ),
    ]
