# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-31 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20171031_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_update',
            field=models.DateTimeField(auto_now=True, verbose_name='房屋信息更新时间'),
        ),
        migrations.AlterField(
            model_name='rentneed',
            name='rent_update',
            field=models.DateTimeField(auto_now=True, verbose_name='租房信息更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_update',
            field=models.DateTimeField(auto_now=True, verbose_name='用户信息更新时间'),
        ),
    ]
